/*
OVERVIEW
    Simulate cars
        A simulated car recieves a random license plate (sometimes on the list, sometimes not)
        and queues up at a random entrace to the car park, triggering an LPR when it reaches 
        the front of the queue.

        After triggering the LPR (license plate reader), the simulated car will watch the 
        digital sign. If the sign contains a number, it will keep note of that number 
        (the level where the car has been instructed to park) and then wait for the boom 
        gate to open. If the sign contains any other character, the simulated car will just 
        leave the queue and drive off, disappearing from the simulation

        After the boom gate opens, the car will drive to the level it was instructed to drive to,
        triggering the level LPR in the process

        The car will then park for a random amount of time

        After the car has finished parking, it will leave, setting off the level LPR again.
        It will then drive towards a random exit. Upon reaching that exit, it will set off the 
        exit LPR and wait for the boom gate to open. Once the boom gate is open, it will leave 
        the car park and disappear from the simulation. 

    Simulate boom gates
        Boom gates take a certain amount of time to open and close. Once the manager has instructed 
        a closed boom gate to open or an open boom gate to close, the simulator's job is to wait for
        a small amount of time before putting the boom gate into the open/closed state.

    Simulate temperature
        Each level of the car park has a temperature sensor, sending back the current temperature 
        (in degrees celsius). THe simulator will frequently update these values with reasonable 
        random values. The simulator should also be able to simulate a fire by generating higher
        values, in order to test / demonstrate the fire alarm system. 

TIMINGS
    Every 1-100ms, a new car will be generated by the simulator with 
    a random license plate, and will start moving towards a random entrance
        Check page 4 of brief for specifics about functions

    Once a car reaches the front of the queue, it will wait 2ms before 
    triggering the entrance LPR

    Boom Gates take 10ms to fully open and close

    After the boom gate is open, the car takes another 10ms to drive 
    to its parking space (which will then trigger the level LPR for the 
    first time)

    Once parked, the car will wait 100-10000ms before departing the level
    (and triggering the level LPR of the second time)

    It then takes the car a further 10ms to drive to a random exit and 
    trigger the exit LPR. 

    Every 1-5ms the temperature on each level will change to a random value

MEMORY
    The simulator must create a shared memory segment named PARKING. 

    The segment is 2920 bytes in size and must be created every time the 
    program runs (overwrite existing)
*/